### ISSUE TITLE
Support for PHPStorm 9

### ISSUE THREAD

**Issue by netconception** [koomai/phpstorm-laravel-live-templates#10]
Good Morning,

can u build in support for upcoming PHPStorm Version 9?

Your current templates are not compatible with it.

Greetings

**Comment by koomai** [comment]
I have yet to try Version 9. Happy for someone else to submit PRs, otherwise it'll have to wait until I get to it.

**Comment by lorvent** [comment]
its already supported for phpstorm 9
you just need to create folder "templates" and copy files into it.
