### ISSUE TITLE
Additional templates for model relationships

### ISSUE THREAD

**Issue by jamesmills** [koomai/phpstorm-laravel-live-templates#18]
Hi,

I was thinking of writing some live templates to help with model relationships and then I came across your repo and thought it might be best to just add them here.

I am having a little issue with this one though https://www.dropbox.com/s/1u4pssojfj6o3mu/Screenshot%202016-03-23%2012.04.17.png?dl=0

Any ideas where I am going wrong?

James

**Comment by koomai** [comment]
That's a great idea, thanks.

What problem are you having - if it's the default value, try wrapping it in double quotes.

**Comment by jamesmills** [comment]
Oh, nice! yes, that worked. But no, that was not my issue. I want to leave the function name as lowercase but have the class name in the hasMany capitalized.
