### ISSUE TITLE
Can't Use Templates

### ISSUE THREAD

**Issue by mehdibahraami** [koomai/phpstorm-laravel-live-templates#21]
Hi,
I'm going in to `Library/Preferences/WebIde100/` but i don't have `templates` folder, i created this folder and download .xml files in to this folder, but i can't use this in phpstorm, i restarted phpstorm and go to live templates but this is not in live templates. please help me.

**Comment by koomai** [comment]
Not sure what the problem could be unless you're looking at the preferences of the wrong version from a previous installation. Note that for newer versions, the folder looks like this **PhpStorm2016.1**.
