### ISSUE TITLE
Collaboration options

### ISSUE THREAD

**Issue by mortenscheel** [koomai/phpstorm-laravel-live-templates#23]
I've enjoyed using your templates for a while now, and I've added my own tweaks here and there.
I don't know if you're interested in receiving pull-requests, but now I'm wondering how it would even be possible (without a LOT of hassle).
Do you have any experience with this?
I've also asked on Reddit: https://www.reddit.com/r/phpstorm/comments/5h6m4m/best_way_to_collaborate_on_live_templates/

**Comment by koomai** [comment]
Absolutely. You can fork this repo, replace the relevant xml files with the ones in your phpstorm config, commit, push and then open a pull request. Thanks!
