### ISSUE TITLE
Not working in 2019.1

### ISSUE THREAD

**Issue by marcosdipaolo** [koomai/phpstorm-laravel-live-templates#32]
Is it checked in 2019.1 version?

**Comment by Tom5om** [comment]
I have the same problem, kinda hope its because of the new version, but its definitely not working

**Comment by koomai** [comment]
Working on 2019.1.1

Try `Cmd+J` otherwise. 

![image](https://user-images.githubusercontent.com/1274618/56740060-8209d480-67b3-11e9-8d93-cae89bf1f349.png)
